### ISSUE TITLE
Wrong date/year for 3 reviews from 23 May 2021?

### ISSUE THREAD

**Issue by Kyunghoonie** [ThereminGoat/switch-scores#5]
Hi! It looks like you published three reviews 5 days ago (according to Github) on 5/23/2021: Durock Sunflower, Gateron Pro Yellow, Gateron Speed Silver Pro but the dates in the actual PDFs have the year "2020". Wasn't sure if this was a typo or not but I thought I'd let you know!

Thanks for the awesome reviews!

**Comment by ThereminGoat** [comment]
Thanks for the keen eye mate. They've been fixed and upload now!
