### ISSUE TITLE
join results...

### ISSUE THREAD

**Issue by g-i-o-r-g-i-o** [ThereminGoat/switch-scores#8]
Suppose that I'm looking for a linear switch that has a deep muted sound... Am I supposed to open all the 400 pdf files? Is there a simpler way to search for the best sounding switch? Maybe an excel or a big fatty file?

Any reason to exclude cherry mx hyperglides?

thanks anyway,very good work

**Comment by ohenryu** [comment]
@GianniGi https://github.com/ThereminGoat/switch-scores/blob/master/Composite%20Score%20Sheet.xlsx

**Comment by g-i-o-r-g-i-o** [comment]
> @GianniGi https://github.com/ThereminGoat/switch-scores/blob/master/Composite%20Score%20Sheet.xlsx

Thanks, I didn't notice the csv files. This is better, it has all the scores: 

https://github.com/ThereminGoat/switch-scores/blob/master/Composite%20Overall%20Total%20Score%20Sheet.csv

Maybe the csv/xls sheet should be among the first ones, or linked directy in the readme?

Probably the csv/xls files could contain links to the pdf files of each switch, otherwise you have to search manually for the files.

Great resource anyway.
